name: Build Kivy APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04  # ⚠️ use 22.04 — 20.04 is deprecated

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y zip unzip openjdk-17-jdk python3-pip git

    - name: Set up Android SDK manually
      run: |
        mkdir -p $HOME/android-sdk/cmdline-tools
        cd $HOME/android-sdk/cmdline-tools
        curl -o sdk-tools.zip https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip
        unzip sdk-tools.zip
        mv cmdline-tools latest
        export PATH=$HOME/android-sdk/cmdline-tools/latest/bin:$PATH
        yes | $HOME/android-sdk/cmdline-tools/latest/bin/sdkmanager --sdk_root=$HOME/android-sdk \
          "platform-tools" \
          "platforms;android-31" \
          "build-tools;30.0.3"
        yes | $HOME/android-sdk/cmdline-tools/latest/bin/sdkmanager --licenses

    - name: Install Buildozer
      run: |
        pip install --upgrade pip
        pip install cython
        pip install buildozer

    - name: Build APK
      run: |
        export ANDROIDSDK=$HOME/android-sdk
        export ANDROID_HOME=$ANDROIDSDK
        export PATH=$ANDROIDSDK/platform-tools:$ANDROIDSDK/cmdline-tools/latest/bin:$PATH

        buildozer init || true
        buildozer android debug

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: CWheadcopyTrainer.apk
        path: bin/*.apk
