name: Build Kivy APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    env:
      ANDROID_SDK_ROOT: $HOME/.buildozer/android/platform/android-sdk

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y zip unzip openjdk-17-jdk python3-pip git libffi-dev \
            libssl-dev libjpeg-dev libpng-dev libfreetype6-dev libpq-dev \
            libsdl2-dev libsdl2-image-dev libsdl2-mixer-dev libsdl2-ttf-dev \
            libportmidi-dev libswscale-dev libavformat-dev libavcodec-dev \
            zlib1g-dev libmtdev-dev libgl1-mesa-dev libgles2-mesa-dev \
            libgstreamer-plugins-base1.0-dev libunwind-dev
          pip install --upgrade pip
          pip install cython buildozer

      - name: Install Android SDK cmdline-tools
        run: |
          mkdir -p $ANDROID_SDK_ROOT/cmdline-tools
          cd $ANDROID_SDK_ROOT/cmdline-tools
          curl -o sdk-tools.zip https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip
          unzip sdk-tools.zip -d temp
          mkdir -p $ANDROID_SDK_ROOT/cmdline-tools/latest
          mv temp/cmdline-tools/* $ANDROID_SDK_ROOT/cmdline-tools/latest

      - name: Accept Android SDK licenses and install build-tools
        run: |
          $ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager --sdk_root=$ANDROID_SDK_ROOT --licenses <<< "y"
          $ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager --sdk_root=$ANDROID_SDK_ROOT \
            "platform-tools" "platforms;android-31" "build-tools;30.0.3"

      - name: Initialize Buildozer
        run: buildozer init || true

      - name: Build APK
        run: buildozer android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: CWheadcopyTrainer.apk
          path: bin/*.apk
