name: Build Kivy APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    env:
      ANDROID_SDK_ROOT: $HOME/.buildozer/android/platform/android-sdk

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Set up Java 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Install system dependencies
        run: |
          sudo apt update
          sudo apt install -y zip unzip openjdk-17-jdk python3-pip git \
            libsdl2-dev libsdl2-image-dev libsdl2-mixer-dev libsdl2-ttf-dev \
            libportmidi-dev libswscale-dev libavformat-dev libavcodec-dev zlib1g-dev \
            libmtdev-dev libgl1-mesa-dev libgles2-mesa-dev libgstreamer-plugins-base1.0-dev \
            libffi-dev libssl-dev libjpeg-dev libpng-dev libfreetype6-dev libpq-dev \
            libunwind-dev

      - name: Install Buildozer and dependencies
        run: |
          pip install --upgrade pip
          pip install buildozer cython

      - name: Download Android command line tools
        run: |
          mkdir -p $ANDROID_SDK_ROOT/cmdline-tools
          curl -o commandlinetools.zip https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip
          unzip -q commandlinetools.zip -d $ANDROID_SDK_ROOT/cmdline-tools/temp
          mkdir -p $ANDROID_SDK_ROOT/cmdline-tools/latest
          mv $ANDROID_SDK_ROOT/cmdline-tools/temp/cmdline-tools/* $ANDROID_SDK_ROOT/cmdline-tools/latest/
          rm -rf $ANDROID_SDK_ROOT/cmdline-tools/temp

      - name: Accept Android SDK licenses
        run: |
          yes | $ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager --sdk_root=$ANDROID_SDK_ROOT --licenses

      - name: Install Android SDK components
        run: |
          yes | $ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager --sdk_root=$ANDROID_SDK_ROOT \
            "platform-tools" "platforms;android-31" "build-tools;30.0.3"

      - name: Initialize Buildozer
        run: |
          buildozer init || true

      - name: Build APK
        run: |
          buildozer android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: CWheadcopyTrainer.apk
          path: bin/*.apk
