January 16, 2019
---------------------------------------
Accept? (y/N): Skipping following packages as the license is not accepted:
Android SDK Build-Tools 36
The following packages can not be installed since their licenses or those of the packages they depend on were not accepted:
  build-tools;36.0.0
[=======================================] 100% Computing updates...             
# Check that aidl can be executed
# build-tools folder not found /home/runner/.buildozer/android/platform/android-sdk/build-tools
# Search for Aidl
# Aidl not found, please install it.
Error: Process completed with exit code 1.
