name: Build Kivy APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    env:
      ANDROID_SDK_ROOT: $HOME/.buildozer/android/platform/android-sdk
      ANDROID_HOME: $HOME/.buildozer/android/platform/android-sdk
      ANDROID_NDK_HOME: $HOME/.buildozer/android/platform/android-ndk-r25b

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y zip unzip openjdk-17-jdk python3-pip git \
              libsdl2-dev libsdl2-image-dev libsdl2-mixer-dev libsdl2-ttf-dev \
              libportmidi-dev libswscale-dev libavformat-dev libavcodec-dev zlib1g-dev \
              libmtdev-dev libgl1-mesa-dev libgles2-mesa-dev \
              libgstreamer-plugins-base1.0-dev libffi-dev libssl-dev libjpeg-dev \
              libpng-dev libfreetype6-dev libpq-dev libunwind-dev

          pip install --upgrade cython buildozer

      - name: Set up Android SDK and NDK
        run: |
          mkdir -p $ANDROID_SDK_ROOT/cmdline-tools
          cd $ANDROID_SDK_ROOT/cmdline-tools

          curl -o sdk-tools.zip https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip
          unzip sdk-tools.zip -d temp
          mv temp/cmdline-tools latest

          # Create 'tools' symlink for compatibility with older scripts
          mkdir -p $ANDROID_SDK_ROOT/cmdline-tools
          ln -sfn $ANDROID_SDK_ROOT/cmdline-tools/latest $ANDROID_SDK_ROOT/cmdline-tools/tools

          export PATH=$ANDROID_SDK_ROOT/cmdline-tools/latest/bin:$PATH

          yes | sdkmanager --sdk_root=$ANDROID_SDK_ROOT \
            "platform-tools" \
            "platforms;android-31" \
            "build-tools;30.0.3" \
            "ndk;25.2.9519653"

          yes | sdkmanager --sdk_root=$ANDROID_SDK_ROOT --licenses

      - name: Build APK with Buildozer
        run: |
          export PATH=$ANDROID_SDK_ROOT/cmdline-tools/latest/bin:$PATH
          buildozer init || true
          buildozer android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: CWheadcopyTrainer.apk
          path: bin/*.apk
